name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TP 2 test
      id: tp2-test
      uses: education/autograding-python-grader@v1
      with:
        timeout: '5'
        max-score: '1'
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TP-2-TEST_RESULTS: "${{steps.tp-2-test.outputs.result}}"
      with:
        runners: tp-2-test
